Repository rtucek/vue-query-builder, pull requests merged in 2022-03, with the labels that each got.

#85 Replace `node-sass` with `sass`
  package.json
  yarn.lock
Labels: dependencies

#84 Remove code coverage upload in PRs
  .github/workflows/ci-testing.yml
Labels: testing

#86 Upgrade dependencies
  yarn.lock
Labels: dependencies

#83 Add Rule Identifier to RuleSlot
  docs/styling.md
  src/QueryBuilderRule.vue
  src/types.ts
  tests/components/Component.vue
  tests/unit/slots.spec.ts
  types/index.d.ts
Labels: documentation, enhancement, testing
